
export interface MesinList {

    KODE : string
    WSID : string
    KDBANK : string
    NMBANK : string
    LOKASI : string
    KETERANGAN : string
    TIPELOKASI : string
    TIPE : string
    MEREK : string
    DNM1 : number
    LBR1 : number
    KET1 : string
    DNM2 : number
    LBR2 : number
    KET2 : string
    DNM3 : number
    LBR3 : number
    KET3 : string
    DNM4 : number
    LBR4 : number
    KET4 : string
    DNM5 : number
    LBR5 : number
    KET5 : string
    DNM6 : number
    LBR6 : number
    KET6 : string
    MAXCTRD : number
    MAXREJECT : number
    STARTTIME : string
    ENDTIME : string
    JAMOPR : string
    LN624 : number
    LN255 : number
    LP624 : number
    LP255 : number
    KDAREACR : string
    NMAREACR : string
    NOURUT : string
    KDAREASV : string
    NMAREASV : string
    KDAREAVD : string
    NMAREAVD : string
    JNSCENCON : string
    AUTOADMIN : number
    STMESIN : number
    LIMITSALDO : number
    KOMPDNM : string
    KOMPCTRD : string
    CATATAN : string
    LATITUDE : string
    LONGITUDE : string
    SINYAL : string
    ADDRESSMAP : string

}
